either/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('pages.urls')),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),

    path('create/', views.create, name='create'),

    path('<int:page_id>/comments/create/', views.comments_create, name='comments_create'),
]

pages/models.py
from django.db import models

# Create your models here.
class Page(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()

class Comment(models.Model):
    content = models.TextField()
    TYPE_SELECT = (
        ('0', 'A'), 
        ('1', 'B'),
        )
    choice = models.CharField(max_length=10, choices=TYPE_SELECT, default='')
    page = models.ForeignKey(Page, on_delete=models.CASCADE, default='')

pages/forms.py
from django import forms
from .models import Page, Comment

class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = '__all__'

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('page',)
        widgets = {
            'choice' : forms.RadioSelect()
        }

pages/views.py
from django.shortcuts import render, redirect
from .models import Page, Comment
from .forms import PageForm, CommentForm

# Create your views here.

def index(request):
    pages = Page.objects.all()
    context = {
        'pages' : pages,
    }
    return render(request, 'pages/index.html', context)

def detail(request, id):
    page = Page.objects.get(id=id)
    comment_form = CommentForm()
    comments = page.comment_set.all()
    
    context = {
        'page' : page,
        'comment_form' : comment_form,
        'comments' : comments,
    }
    return render(request, 'pages/detail.html', context)

def create(request):
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            page = form.save()
            return redirect('pages:detail', id=page.id)
    else:
        form = PageForm()
    context = {
        'form' : form,
    }
    return render(request, 'pages/form.html', context)

def comments_create(request, page_id):
    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.page_id = page_id
            comment.save()
            return redirect('pages:detail', page_id)

    else:
        return redirect('pages:detail', page_id)
    

pages/templates/pages/detail.html
{% extends 'base.html' %}

{% block content %}

<h2>{{page.title}}</h2>
<p>{{page.content}}</p>
<hr>

<h3>comments</h3>
{% for comment in comments %}
    <p>{{comment.content}} <b>[{{comment.get_choice_display}} 선택]</b></p>
{% endfor %}
<hr>

<form action="{% url 'pages:comments_create' page.id %}" method="POST">
    {% csrf_token %}
    {{comment_form}}
    <input type="submit">
</form>
<hr>

{% endblock %}

pages/templates/pages/form.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}

    <div class="mb-3">
        <label for="title" class="form-label">Title</label>
        <input type="text" class="form-control" id="title" name="title" >
    </div>
    <div class="mb-3">
        <label for="content" class="form-label">Content</label>
        <textarea class="form-control" id="content" rows="3" name="content"></textarea>
    </div>
    
    <input type="submit">
</form>

{% endblock %}

pages/templates/pages/index.html
{% extends 'base.html' %}

{% block content %}
<h1>index</h1>
{% for page in pages %}
    <a href="{% url 'pages:detail' id=page.id %}">[글번호{{page.id}}] {{page.title}}</a>
    <hr>
{% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'pages:index' %}">Home</a>
                <a class="nav-link" href="{% url 'pages:create' %}">New</a>
              </div>
            </div>
          </div>
    </nav>
    <div class="container">
        {% block content %}
        
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>